# Generated by Django 4.2.7 on 2026-08-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplyClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the user clicked apply"
                    ),
                ),
                (
                    "event_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional event metadata for analytics",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apply_clicks",
                        to="jobs.job",
                        verbose_name="Job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apply Click",
                "verbose_name_plural": "Apply Clicks",
                "db_table": "apply_clicks",
                "ordering": ["-clicked_at"],
            },
        ),
    ]
