# Generated by Django 4.2.7 on 2026-08-29 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="applyclick",
            name="user",
            field=models.ForeignKey(
                help_text="User who clicked apply (nullable for anonymous tracking if needed)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="apply_clicks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
