# Generated by Django 4.2.7 on 2026-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="applyclick",
            index=models.Index(
                fields=["job", "-clicked_at"], name="idx_applyclick_job_clicked_at"
            ),
        ),
        migrations.AddIndex(
            model_name="applyclick",
            index=models.Index(
                fields=["user", "-clicked_at"], name="idx_applyclick_user_clicked_at"
            ),
        ),
    ]
