# Generated by Django 5.2.12 on 2026-06-16 23:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resumeversion_unique_version_number_per_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructuredResume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='structured_resume', to='resumes.resumeversion')),
            ],
            options={
                'verbose_name': 'structured resume',
                'verbose_name_plural': 'structured resumes',
                'db_table': 'structured_resumes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('structured_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resumes.structuredresume')),
            ],
            options={
                'verbose_name': 'resume skill',
                'verbose_name_plural': 'resume skills',
                'db_table': 'resume_skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResumeProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('project_url', models.URLField(blank=True)),
                ('structured_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resumes.structuredresume')),
            ],
            options={
                'verbose_name': 'resume project',
                'verbose_name_plural': 'resume projects',
                'db_table': 'resume_projects',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ResumeExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('structured_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='resumes.structuredresume')),
            ],
            options={
                'verbose_name': 'resume experience',
                'verbose_name_plural': 'resume experience',
                'db_table': 'resume_experience',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=255)),
                ('start_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('structured_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resumes.structuredresume')),
            ],
            options={
                'verbose_name': 'resume education',
                'verbose_name_plural': 'resume education',
                'db_table': 'resume_education',
                'ordering': ['-end_year'],
            },
        ),
        migrations.CreateModel(
            name='ResumeCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('structured_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='resumes.structuredresume')),
            ],
            options={
                'verbose_name': 'resume certification',
                'verbose_name_plural': 'resume certifications',
                'db_table': 'resume_certifications',
                'ordering': ['-issue_date'],
            },
        ),
    ]
