# Generated by Django 5.1.7 on 2026-06-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("candidate", "Candidate"),
                    ("recruiter", "Recruiter"),
                    ("admin", "Admin"),
                ],
                default="candidate",
                max_length=32,
            ),
        ),
    ]
