# Generated by Django 4.2.7 on 2026-08-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of normalized broader terms for keyword/domain overlap",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="skills",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of normalized concrete skills/capabilities/technologies",
            ),
        ),
    ]
