# Generated by Django 4.2.7 on 2026-08-30 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_keywords_alter_userprofile_skills"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
