# Generated by Django 4.2.7 on 2026-08-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Optional username (kept for compatibility with AbstractUser)",
                max_length=150,
                null=True,
            ),
        ),
    ]
