from django.urls import path

from .views import (
    ResumeUploadView,
    ResumeListView,
    ResumeDetailView,
    ActiveResumeView,
    ResumeActivateView,
    ParseResumeView,
    ParsedResumeDetailView,
    ResumeVersionHistoryView,
    CurrentResumeVersionView,
    RollbackResumeVersionView,
    ParseResumeVersionView,
    ParsedResumeVersionDetailView,
    ExtractResumeVersionView,
    StructuredResumeVersionView,
    ResumeSearchView,
    CandidateProfileView,
    CandidateSearchView,
)

urlpatterns = [
    path("upload/", ResumeUploadView.as_view(), name="resume-upload"),
    path("", ResumeListView.as_view(), name="resume-list"),
    path("<uuid:id>/", ResumeDetailView.as_view(), name="resume-detail"),
    path("<uuid:id>/activate/", ResumeActivateView.as_view(), name="resume-activate"),
    path("<uuid:id>/parse/", ParseResumeView.as_view(), name="resume-parse"),
    path("<uuid:id>/parsed/", ParsedResumeDetailView.as_view(), name="resume-parsed"),
    path("active/", ActiveResumeView.as_view(), name="resume-active"),
    path("<uuid:id>/versions/", ResumeVersionHistoryView.as_view(), name="resume-version-history"),
    path("<uuid:id>/versions/current/", CurrentResumeVersionView.as_view(), name="resume-version-current"),
    path("<uuid:id>/versions/<uuid:version_id>/rollback/", RollbackResumeVersionView.as_view(), name="resume-version-rollback"),
    path("<uuid:id>/versions/<uuid:version_id>/activate/", ResumeActivateView.as_view(), name="resume-version-activate"),
    path("versions/<uuid:version_id>/parse/", ParseResumeVersionView.as_view(), name="resume-version-parse"),
    path("versions/<uuid:version_id>/parsed/", ParsedResumeVersionDetailView.as_view(), name="resume-version-parsed"),
    path("versions/<uuid:version_id>/extract/", ExtractResumeVersionView.as_view(), name="resume-version-extract"),
    path("versions/<uuid:version_id>/structured/", StructuredResumeVersionView.as_view(), name="resume-version-structured"),
    path("search/", ResumeSearchView.as_view(), name="resume-search"),
    path("candidates/<uuid:candidate_id>/", CandidateProfileView.as_view(), name="candidate-profile"),
    path("candidates/search/", CandidateSearchView.as_view(), name="candidate-search"),
]
