# Generated by Django 4.2.7 on 2026-08-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("PRO", "Pro"),
                            ("PREMIUM", "Premium"),
                        ],
                        default="FREE",
                        help_text="Subscription plan",
                        max_length=20,
                    ),
                ),
                (
                    "provider_subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment provider subscription identifier (e.g., Razorpay subscription ID)",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                            ("PENDING", "Pending"),
                        ],
                        default="ACTIVE",
                        help_text="Subscription status",
                        max_length=20,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(help_text="When the subscription started"),
                ),
                (
                    "expiration_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the subscription expires or renews",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "db_table": "subscriptions",
            },
        ),
    ]
