# Generated by Django 4.2.7 on 2026-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="idx_subscription_status"),
        ),
    ]
