# Generated by Django 5.2.12 on 2026-06-24 02:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skills_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('education_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('matched_skills_count', models.PositiveIntegerField(default=0)),
                ('total_required_skills', models.PositiveIntegerField(default=0)),
                ('explanation', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(limit_choices_to={'role': 'candidate'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='jobs.job')),
            ],
            options={
                'db_table': 'job_matches',
                'ordering': ['-match_score'],
                'indexes': [models.Index(fields=['candidate'], name='job_matches_candida_aeb8ad_idx'), models.Index(fields=['job'], name='job_matches_job_id_3ba270_idx'), models.Index(fields=['match_score'], name='job_matches_match_s_c4667a_idx')],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'job'), name='unique_candidate_job_match', violation_error_message='A candidate can only have one match record per job.')],
            },
        ),
    ]
