# Generated by Django 4.2.7 on 2026-08-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Final match score (0.0 to 1.0)",
                        max_digits=5,
                    ),
                ),
                (
                    "skill_similarity_score",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Skill similarity component (50% weight)",
                        max_digits=5,
                    ),
                ),
                (
                    "experience_match_score",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Experience match component (30% weight)",
                        max_digits=5,
                    ),
                ),
                (
                    "keyword_overlap_score",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Keyword overlap component (20% weight)",
                        max_digits=5,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Version of the match score for tracking updates",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this match score was first calculated",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this match score was last recalculated",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_scores",
                        to="jobs.job",
                        verbose_name="Job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Match Score",
                "verbose_name_plural": "Match Scores",
                "db_table": "match_scores",
                "ordering": ["-final_score"],
            },
        ),
    ]
