# Generated by Django 4.2.7 on 2026-08-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matching", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchscore",
            name="user_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match_scores",
                to="users.userprofile",
                verbose_name="User Profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchscore",
            constraint=models.UniqueConstraint(
                fields=("user_profile", "job", "version"),
                name="unique_user_job_version",
            ),
        ),
    ]
