# Generated by Django 5.1.7 on 2026-07-23 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0002_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="jobmatch",
            name="jobmatch_job_match_score_idx",
        ),
        migrations.RemoveIndex(
            model_name="jobmatch",
            name="jobmatch_candidate_job_idx",
        ),
    ]
