# Generated by Django 4.2.7 on 2026-08-29 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchscore",
            name="experience_match_score",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Experience match component (30% weight)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="matchscore",
            name="final_score",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Final match score (0.0 to 1.0)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="matchscore",
            name="keyword_overlap_score",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Keyword overlap component (20% weight)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="matchscore",
            name="skill_similarity_score",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Skill similarity component (50% weight)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
