# Generated by Django 4.2.7 on 2026-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0003_alter_matchscore_experience_match_score_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="matchscore",
            index=models.Index(
                fields=["user_profile", "-final_score"], name="idx_match_profile_score"
            ),
        ),
        migrations.AddIndex(
            model_name="matchscore",
            index=models.Index(
                fields=["user_profile", "job"], name="idx_match_profile_job"
            ),
        ),
        migrations.AddIndex(
            model_name="matchscore",
            index=models.Index(fields=["-updated_at"], name="idx_match_updated_at"),
        ),
        migrations.AddConstraint(
            model_name="matchscore",
            constraint=models.CheckConstraint(
                check=models.Q(("final_score__gte", 0), ("final_score__lte", 1)),
                name="final_score_range",
                violation_error_message="Final score must be between 0.0 and 1.0",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchscore",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("skill_similarity_score__gte", 0),
                    ("skill_similarity_score__lte", 1),
                ),
                name="skill_similarity_score_range",
                violation_error_message="Skill similarity score must be between 0.0 and 1.0",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchscore",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("experience_match_score__gte", 0),
                    ("experience_match_score__lte", 1),
                ),
                name="experience_match_score_range",
                violation_error_message="Experience match score must be between 0.0 and 1.0",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchscore",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("keyword_overlap_score__gte", 0), ("keyword_overlap_score__lte", 1)
                ),
                name="keyword_overlap_score_range",
                violation_error_message="Keyword overlap score must be between 0.0 and 1.0",
            ),
        ),
    ]
