# Generated by Django 4.2.7 on 2026-08-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0004_matchscore_idx_match_profile_score_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="matchscore",
            name="idx_match_profile_job",
        ),
    ]
