# Generated by Django 4.2.7 on 2026-08-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_job_id",
                    models.CharField(
                        help_text="External job identifier from the source system",
                        max_length=200,
                    ),
                ),
                ("title", models.CharField(help_text="Job title", max_length=300)),
                ("description", models.TextField(help_text="Job description")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Job location (city, state/country, or remote)",
                        max_length=200,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FULL_TIME", "Full-time"),
                            ("PART_TIME", "Part-time"),
                            ("CONTRACT", "Contract"),
                            ("INTERNSHIP", "Internship"),
                            ("REMOTE", "Remote"),
                        ],
                        help_text="Type of employment",
                        max_length=50,
                    ),
                ),
                (
                    "experience_required",
                    models.CharField(
                        blank=True,
                        help_text='Required experience level (e.g., "3-5 years", "Senior")',
                        max_length=200,
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of required and preferred skills",
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extracted keywords for matching",
                    ),
                ),
                (
                    "application_url",
                    models.URLField(
                        help_text="Official company application URL for this job",
                        max_length=500,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Source URL where the job was found (if distinct from application URL)",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        help_text="Job status",
                        max_length=20,
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the job was first discovered"
                    ),
                ),
                (
                    "last_fetched_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the job was last fetched from the source",
                    ),
                ),
                (
                    "deduplication_hash",
                    models.CharField(
                        help_text="Deterministic hash for deduplication",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "is_sponsored",
                    models.BooleanField(
                        default=False, help_text="Whether this job is sponsored"
                    ),
                ),
                (
                    "job_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured metadata from job processing",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "db_table": "jobs",
                "ordering": ["-first_seen_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                fields=("company", "external_job_id"),
                name="unique_company_external_job",
            ),
        ),
    ]
