# Generated by Django 4.2.7 on 2026-08-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="maximum_experience_years",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Maximum years of experience required (numeric)",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="minimum_experience_years",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Minimum years of experience required (numeric)",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="keywords",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of normalized broader terms for keyword/domain overlap",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of normalized concrete skills/capabilities/technologies",
            ),
        ),
    ]
