# Generated by Django 4.2.7 on 2026-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_maximum_experience_years_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["status"], name="idx_job_status"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "-last_fetched_at"], name="idx_job_status_freshness"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["deduplication_hash"], name="idx_job_deduplication_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("minimum_experience_years__isnull", True),
                    ("maximum_experience_years__isnull", True),
                    (
                        "minimum_experience_years__lte",
                        models.F("maximum_experience_years"),
                    ),
                    _connector="OR",
                ),
                name="valid_experience_range",
                violation_error_message="Minimum experience years must be less than or equal to maximum experience years when both are specified",
            ),
        ),
    ]
