# Generated by Django 5.1.7 on 2026-07-23 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="job",
            name="jobs_status_created_at_idx",
        ),
    ]
