# Generated by Django 4.2.7 on 2026-08-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_idx_job_status_job_idx_job_status_freshness_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="job",
            name="idx_job_status",
        ),
        migrations.RemoveIndex(
            model_name="job",
            name="idx_job_deduplication_hash",
        ),
    ]
