# Generated by Django 4.2.7 on 2026-08-30 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_idx_company_is_active"),
        ("jobs", "0004_remove_job_idx_job_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source identifier from registry", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="Ingestion run status",
                        max_length=20,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID if executed via Celery",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the ingestion run started",
                        null=True,
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the ingestion run finished",
                        null=True,
                    ),
                ),
                (
                    "fetched_count",
                    models.IntegerField(
                        default=0, help_text="Number of jobs fetched from source"
                    ),
                ),
                (
                    "normalized_count",
                    models.IntegerField(
                        default=0, help_text="Number of jobs normalized successfully"
                    ),
                ),
                (
                    "created_count",
                    models.IntegerField(
                        default=0, help_text="Number of new jobs created"
                    ),
                ),
                (
                    "updated_count",
                    models.IntegerField(
                        default=0, help_text="Number of existing jobs updated"
                    ),
                ),
                (
                    "skipped_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of jobs skipped (validation/integrity errors)",
                    ),
                ),
                (
                    "failed_count",
                    models.IntegerField(
                        default=0, help_text="Number of jobs that failed to ingest"
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of error if run failed",
                        max_length=100,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if run failed (bounded size, no secrets)",
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Number of retry attempts for this run"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestion_runs",
                        to="companies.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingestion Run",
                "verbose_name_plural": "Ingestion Runs",
                "db_table": "ingestion_runs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "status"], name="idx_ing_run_src_status"
                    ),
                    models.Index(fields=["started_at"], name="idx_ing_run_started"),
                    models.Index(
                        fields=["source", "started_at"], name="idx_ing_run_src_start"
                    ),
                    models.Index(fields=["task_id"], name="idx_ing_run_task_id"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="ingestionrun",
            constraint=models.CheckConstraint(
                check=models.Q(("fetched_count__gte", 0)),
                name="check_fetched_count_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionrun",
            constraint=models.CheckConstraint(
                check=models.Q(("normalized_count__gte", 0)),
                name="check_normalized_count_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionrun",
            constraint=models.CheckConstraint(
                check=models.Q(("created_count__gte", 0)),
                name="check_created_count_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionrun",
            constraint=models.CheckConstraint(
                check=models.Q(("updated_count__gte", 0)),
                name="check_updated_count_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionrun",
            constraint=models.CheckConstraint(
                check=models.Q(("skipped_count__gte", 0)),
                name="check_skipped_count_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionrun",
            constraint=models.CheckConstraint(
                check=models.Q(("failed_count__gte", 0)),
                name="check_failed_count_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionrun",
            constraint=models.CheckConstraint(
                check=models.Q(("retry_count__gte", 0)),
                name="check_retry_count_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionrun",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("finished_at__isnull", True),
                    ("started_at__isnull", True),
                    ("finished_at__gte", models.F("started_at")),
                    _connector="OR",
                ),
                name="check_finished_after_started",
            ),
        ),
    ]
