# Generated by Django 4.2.7 on 2026-08-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_ingestionrun_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ingestionrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "RUNNING")),
                fields=("source",),
                name="unique_running_per_source",
                violation_error_message="An ingestion run is already in progress for this source",
            ),
        ),
    ]
