# Generated by Django 4.2.7 on 2026-08-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_ingestionrun_unique_running_per_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestionrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("RETRYING", "Retrying"),
                    ("SUCCEEDED", "Succeeded"),
                    ("PARTIAL", "Partial"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                help_text="Ingestion run status",
                max_length=20,
            ),
        ),
    ]
