# Generated by Django 4.2.7 on 2026-08-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Company name", max_length=200, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier for the company",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "careers_url",
                    models.URLField(
                        help_text="Official company careers page URL", max_length=500
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this company source is active for job fetching",
                    ),
                ),
                (
                    "scraper_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuration for the scraper implementation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "db_table": "companies",
                "ordering": ["name"],
            },
        ),
    ]
