# Generated by Django 4.2.7 on 2026-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["is_active"], name="idx_company_is_active"),
        ),
    ]
