# Generated by Django 5.2.12 on 2026-06-23 23:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        ("resumes", "0003_structuredresume_resumeskill_resumeproject_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("shortlisted", "Shortlisted"),
                            ("rejected", "Rejected"),
                            ("hired", "Hired"),
                        ],
                        default="submitted",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        limit_choices_to={"role": "candidate"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
                (
                    "resume_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="resumes.resumeversion",
                    ),
                ),
            ],
            options={
                "db_table": "applications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="application_status_e61111_idx"
                    ),
                    models.Index(fields=["job"], name="application_job_id_c2a30a_idx"),
                    models.Index(
                        fields=["candidate"], name="application_candida_0452de_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="application_created_a07231_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "candidate"),
                        name="unique_application_per_job_candidate",
                        violation_error_message="A candidate may only apply once per job.",
                    )
                ],
            },
        ),
    ]
