# Generated by Django 5.1.7 on 2026-07-23 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_applicationstatushistory"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="application",
            name="applications_job_status_idx",
        ),
    ]
